// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace communication {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class Request;
class Request_Begin;
class Request_Get;
class Request_Put;
class Request_Put_Tuple;
class Response;

// ===================================================================

class Request_Begin : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Request.Begin) */ {
 public:
  Request_Begin();
  virtual ~Request_Begin();

  Request_Begin(const Request_Begin& from);

  inline Request_Begin& operator=(const Request_Begin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_Begin& default_instance();

  void Swap(Request_Begin* other);

  // implements Message ----------------------------------------------

  inline Request_Begin* New() const { return New(NULL); }

  Request_Begin* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_Begin& from);
  void MergeFrom(const Request_Begin& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request_Begin* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // @@protoc_insertion_point(class_scope:communication.Request.Begin)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Request_Begin* default_instance_;
};
// -------------------------------------------------------------------

class Request_Get : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Request.Get) */ {
 public:
  Request_Get();
  virtual ~Request_Get();

  Request_Get(const Request_Get& from);

  inline Request_Get& operator=(const Request_Get& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_Get& default_instance();

  void Swap(Request_Get* other);

  // implements Message ----------------------------------------------

  inline Request_Get* New() const { return New(NULL); }

  Request_Get* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_Get& from);
  void MergeFrom(const Request_Get& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request_Get* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // required string key = 2;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 2;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional int64 timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:communication.Request.Get)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::int64 timestamp_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Request_Get* default_instance_;
};
// -------------------------------------------------------------------

class Request_Put_Tuple : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Request.Put.Tuple) */ {
 public:
  Request_Put_Tuple();
  virtual ~Request_Put_Tuple();

  Request_Put_Tuple(const Request_Put_Tuple& from);

  inline Request_Put_Tuple& operator=(const Request_Put_Tuple& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_Put_Tuple& default_instance();

  void Swap(Request_Put_Tuple* other);

  // implements Message ----------------------------------------------

  inline Request_Put_Tuple* New() const { return New(NULL); }

  Request_Put_Tuple* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_Put_Tuple& from);
  void MergeFrom(const Request_Put_Tuple& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request_Put_Tuple* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // required int64 timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:communication.Request.Put.Tuple)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int64 timestamp_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Request_Put_Tuple* default_instance_;
};
// -------------------------------------------------------------------

class Request_Put : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Request.Put) */ {
 public:
  Request_Put();
  virtual ~Request_Put();

  Request_Put(const Request_Put& from);

  inline Request_Put& operator=(const Request_Put& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_Put& default_instance();

  void Swap(Request_Put* other);

  // implements Message ----------------------------------------------

  inline Request_Put* New() const { return New(NULL); }

  Request_Put* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_Put& from);
  void MergeFrom(const Request_Put& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request_Put* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_Put_Tuple Tuple;

  // accessors -------------------------------------------------------

  // required string type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // repeated .communication.Request.Put.Tuple tuple = 2;
  int tuple_size() const;
  void clear_tuple();
  static const int kTupleFieldNumber = 2;
  const ::communication::Request_Put_Tuple& tuple(int index) const;
  ::communication::Request_Put_Tuple* mutable_tuple(int index);
  ::communication::Request_Put_Tuple* add_tuple();
  ::google::protobuf::RepeatedPtrField< ::communication::Request_Put_Tuple >*
      mutable_tuple();
  const ::google::protobuf::RepeatedPtrField< ::communication::Request_Put_Tuple >&
      tuple() const;

  // @@protoc_insertion_point(class_scope:communication.Request.Put)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::RepeatedPtrField< ::communication::Request_Put_Tuple > tuple_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Request_Put* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  inline Request* New() const { return New(NULL); }

  Request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_Begin Begin;
  typedef Request_Get Get;
  typedef Request_Put Put;

  // accessors -------------------------------------------------------

  // optional .communication.Request.Begin begin = 1;
  bool has_begin() const;
  void clear_begin();
  static const int kBeginFieldNumber = 1;
  const ::communication::Request_Begin& begin() const;
  ::communication::Request_Begin* mutable_begin();
  ::communication::Request_Begin* release_begin();
  void set_allocated_begin(::communication::Request_Begin* begin);

  // optional .communication.Request.Get get = 2;
  bool has_get() const;
  void clear_get();
  static const int kGetFieldNumber = 2;
  const ::communication::Request_Get& get() const;
  ::communication::Request_Get* mutable_get();
  ::communication::Request_Get* release_get();
  void set_allocated_get(::communication::Request_Get* get);

  // optional .communication.Request.Put put = 3;
  bool has_put() const;
  void clear_put();
  static const int kPutFieldNumber = 3;
  const ::communication::Request_Put& put() const;
  ::communication::Request_Put* mutable_put();
  ::communication::Request_Put* release_put();
  void set_allocated_put(::communication::Request_Put* put);

  // @@protoc_insertion_point(class_scope:communication.Request)
 private:
  inline void set_has_begin();
  inline void clear_has_begin();
  inline void set_has_get();
  inline void clear_has_get();
  inline void set_has_put();
  inline void clear_has_put();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::communication::Request_Begin* begin_;
  ::communication::Request_Get* get_;
  ::communication::Request_Put* put_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:communication.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  void Swap(Response* other);

  // implements Message ----------------------------------------------

  inline Response* New() const { return New(NULL); }

  Response* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool err = 1 [default = false];
  bool has_err() const;
  void clear_err();
  static const int kErrFieldNumber = 1;
  bool err() const;
  void set_err(bool value);

  // optional bool succeed = 2;
  bool has_succeed() const;
  void clear_succeed();
  static const int kSucceedFieldNumber = 2;
  bool succeed() const;
  void set_succeed(bool value);

  // optional string value = 3;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 3;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // optional int64 timestamp = 4;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 4;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:communication.Response)
 private:
  inline void set_has_err();
  inline void clear_has_err();
  inline void set_has_succeed();
  inline void clear_has_succeed();
  inline void set_has_value();
  inline void clear_has_value();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::int64 timestamp_;
  bool err_;
  bool succeed_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Response* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Request_Begin

// required string type = 1;
inline bool Request_Begin::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_Begin::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_Begin::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_Begin::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& Request_Begin::type() const {
  // @@protoc_insertion_point(field_get:communication.Request.Begin.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Begin::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Begin.type)
}
inline void Request_Begin::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Begin.type)
}
inline void Request_Begin::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Begin.type)
}
inline ::std::string* Request_Begin::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:communication.Request.Begin.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Begin::release_type() {
  // @@protoc_insertion_point(field_release:communication.Request.Begin.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Begin::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Begin.type)
}

// -------------------------------------------------------------------

// Request_Get

// required string type = 1;
inline bool Request_Get::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_Get::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_Get::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_Get::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& Request_Get::type() const {
  // @@protoc_insertion_point(field_get:communication.Request.Get.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Get::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Get.type)
}
inline void Request_Get::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Get.type)
}
inline void Request_Get::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Get.type)
}
inline ::std::string* Request_Get::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:communication.Request.Get.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Get::release_type() {
  // @@protoc_insertion_point(field_release:communication.Request.Get.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Get::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Get.type)
}

// required string key = 2;
inline bool Request_Get::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request_Get::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request_Get::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request_Get::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& Request_Get::key() const {
  // @@protoc_insertion_point(field_get:communication.Request.Get.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Get::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Get.key)
}
inline void Request_Get::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Get.key)
}
inline void Request_Get::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Get.key)
}
inline ::std::string* Request_Get::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:communication.Request.Get.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Get::release_key() {
  // @@protoc_insertion_point(field_release:communication.Request.Get.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Get::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Get.key)
}

// optional int64 timestamp = 3;
inline bool Request_Get::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request_Get::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request_Get::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request_Get::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 Request_Get::timestamp() const {
  // @@protoc_insertion_point(field_get:communication.Request.Get.timestamp)
  return timestamp_;
}
inline void Request_Get::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:communication.Request.Get.timestamp)
}

// -------------------------------------------------------------------

// Request_Put_Tuple

// required string key = 1;
inline bool Request_Put_Tuple::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_Put_Tuple::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_Put_Tuple::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_Put_Tuple::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& Request_Put_Tuple::key() const {
  // @@protoc_insertion_point(field_get:communication.Request.Put.Tuple.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put_Tuple::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Put.Tuple.key)
}
inline void Request_Put_Tuple::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Put.Tuple.key)
}
inline void Request_Put_Tuple::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Put.Tuple.key)
}
inline ::std::string* Request_Put_Tuple::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:communication.Request.Put.Tuple.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Put_Tuple::release_key() {
  // @@protoc_insertion_point(field_release:communication.Request.Put.Tuple.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put_Tuple::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Put.Tuple.key)
}

// required string value = 2;
inline bool Request_Put_Tuple::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request_Put_Tuple::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request_Put_Tuple::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request_Put_Tuple::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Request_Put_Tuple::value() const {
  // @@protoc_insertion_point(field_get:communication.Request.Put.Tuple.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put_Tuple::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Put.Tuple.value)
}
inline void Request_Put_Tuple::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Put.Tuple.value)
}
inline void Request_Put_Tuple::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Put.Tuple.value)
}
inline ::std::string* Request_Put_Tuple::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:communication.Request.Put.Tuple.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Put_Tuple::release_value() {
  // @@protoc_insertion_point(field_release:communication.Request.Put.Tuple.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put_Tuple::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Put.Tuple.value)
}

// required int64 timestamp = 3;
inline bool Request_Put_Tuple::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request_Put_Tuple::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request_Put_Tuple::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request_Put_Tuple::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 Request_Put_Tuple::timestamp() const {
  // @@protoc_insertion_point(field_get:communication.Request.Put.Tuple.timestamp)
  return timestamp_;
}
inline void Request_Put_Tuple::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:communication.Request.Put.Tuple.timestamp)
}

// -------------------------------------------------------------------

// Request_Put

// required string type = 1;
inline bool Request_Put::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_Put::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_Put::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_Put::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& Request_Put::type() const {
  // @@protoc_insertion_point(field_get:communication.Request.Put.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Request.Put.type)
}
inline void Request_Put::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Request.Put.type)
}
inline void Request_Put::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Request.Put.type)
}
inline ::std::string* Request_Put::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:communication.Request.Put.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request_Put::release_type() {
  // @@protoc_insertion_point(field_release:communication.Request.Put.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request_Put::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:communication.Request.Put.type)
}

// repeated .communication.Request.Put.Tuple tuple = 2;
inline int Request_Put::tuple_size() const {
  return tuple_.size();
}
inline void Request_Put::clear_tuple() {
  tuple_.Clear();
}
inline const ::communication::Request_Put_Tuple& Request_Put::tuple(int index) const {
  // @@protoc_insertion_point(field_get:communication.Request.Put.tuple)
  return tuple_.Get(index);
}
inline ::communication::Request_Put_Tuple* Request_Put::mutable_tuple(int index) {
  // @@protoc_insertion_point(field_mutable:communication.Request.Put.tuple)
  return tuple_.Mutable(index);
}
inline ::communication::Request_Put_Tuple* Request_Put::add_tuple() {
  // @@protoc_insertion_point(field_add:communication.Request.Put.tuple)
  return tuple_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::communication::Request_Put_Tuple >*
Request_Put::mutable_tuple() {
  // @@protoc_insertion_point(field_mutable_list:communication.Request.Put.tuple)
  return &tuple_;
}
inline const ::google::protobuf::RepeatedPtrField< ::communication::Request_Put_Tuple >&
Request_Put::tuple() const {
  // @@protoc_insertion_point(field_list:communication.Request.Put.tuple)
  return tuple_;
}

// -------------------------------------------------------------------

// Request

// optional .communication.Request.Begin begin = 1;
inline bool Request::has_begin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_begin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_begin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_begin() {
  if (begin_ != NULL) begin_->::communication::Request_Begin::Clear();
  clear_has_begin();
}
inline const ::communication::Request_Begin& Request::begin() const {
  // @@protoc_insertion_point(field_get:communication.Request.begin)
  return begin_ != NULL ? *begin_ : *default_instance_->begin_;
}
inline ::communication::Request_Begin* Request::mutable_begin() {
  set_has_begin();
  if (begin_ == NULL) {
    begin_ = new ::communication::Request_Begin;
  }
  // @@protoc_insertion_point(field_mutable:communication.Request.begin)
  return begin_;
}
inline ::communication::Request_Begin* Request::release_begin() {
  // @@protoc_insertion_point(field_release:communication.Request.begin)
  clear_has_begin();
  ::communication::Request_Begin* temp = begin_;
  begin_ = NULL;
  return temp;
}
inline void Request::set_allocated_begin(::communication::Request_Begin* begin) {
  delete begin_;
  begin_ = begin;
  if (begin) {
    set_has_begin();
  } else {
    clear_has_begin();
  }
  // @@protoc_insertion_point(field_set_allocated:communication.Request.begin)
}

// optional .communication.Request.Get get = 2;
inline bool Request::has_get() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_get() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_get() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_get() {
  if (get_ != NULL) get_->::communication::Request_Get::Clear();
  clear_has_get();
}
inline const ::communication::Request_Get& Request::get() const {
  // @@protoc_insertion_point(field_get:communication.Request.get)
  return get_ != NULL ? *get_ : *default_instance_->get_;
}
inline ::communication::Request_Get* Request::mutable_get() {
  set_has_get();
  if (get_ == NULL) {
    get_ = new ::communication::Request_Get;
  }
  // @@protoc_insertion_point(field_mutable:communication.Request.get)
  return get_;
}
inline ::communication::Request_Get* Request::release_get() {
  // @@protoc_insertion_point(field_release:communication.Request.get)
  clear_has_get();
  ::communication::Request_Get* temp = get_;
  get_ = NULL;
  return temp;
}
inline void Request::set_allocated_get(::communication::Request_Get* get) {
  delete get_;
  get_ = get;
  if (get) {
    set_has_get();
  } else {
    clear_has_get();
  }
  // @@protoc_insertion_point(field_set_allocated:communication.Request.get)
}

// optional .communication.Request.Put put = 3;
inline bool Request::has_put() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_put() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_put() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_put() {
  if (put_ != NULL) put_->::communication::Request_Put::Clear();
  clear_has_put();
}
inline const ::communication::Request_Put& Request::put() const {
  // @@protoc_insertion_point(field_get:communication.Request.put)
  return put_ != NULL ? *put_ : *default_instance_->put_;
}
inline ::communication::Request_Put* Request::mutable_put() {
  set_has_put();
  if (put_ == NULL) {
    put_ = new ::communication::Request_Put;
  }
  // @@protoc_insertion_point(field_mutable:communication.Request.put)
  return put_;
}
inline ::communication::Request_Put* Request::release_put() {
  // @@protoc_insertion_point(field_release:communication.Request.put)
  clear_has_put();
  ::communication::Request_Put* temp = put_;
  put_ = NULL;
  return temp;
}
inline void Request::set_allocated_put(::communication::Request_Put* put) {
  delete put_;
  put_ = put;
  if (put) {
    set_has_put();
  } else {
    clear_has_put();
  }
  // @@protoc_insertion_point(field_set_allocated:communication.Request.put)
}

// -------------------------------------------------------------------

// Response

// optional bool err = 1 [default = false];
inline bool Response::has_err() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::set_has_err() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Response::clear_has_err() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Response::clear_err() {
  err_ = false;
  clear_has_err();
}
inline bool Response::err() const {
  // @@protoc_insertion_point(field_get:communication.Response.err)
  return err_;
}
inline void Response::set_err(bool value) {
  set_has_err();
  err_ = value;
  // @@protoc_insertion_point(field_set:communication.Response.err)
}

// optional bool succeed = 2;
inline bool Response::has_succeed() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::set_has_succeed() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Response::clear_has_succeed() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Response::clear_succeed() {
  succeed_ = false;
  clear_has_succeed();
}
inline bool Response::succeed() const {
  // @@protoc_insertion_point(field_get:communication.Response.succeed)
  return succeed_;
}
inline void Response::set_succeed(bool value) {
  set_has_succeed();
  succeed_ = value;
  // @@protoc_insertion_point(field_set:communication.Response.succeed)
}

// optional string value = 3;
inline bool Response::has_value() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Response::set_has_value() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Response::clear_has_value() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Response::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& Response::value() const {
  // @@protoc_insertion_point(field_get:communication.Response.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:communication.Response.value)
}
inline void Response::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:communication.Response.value)
}
inline void Response::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:communication.Response.value)
}
inline ::std::string* Response::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:communication.Response.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_value() {
  // @@protoc_insertion_point(field_release:communication.Response.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:communication.Response.value)
}

// optional int64 timestamp = 4;
inline bool Response::has_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Response::set_has_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Response::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Response::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 Response::timestamp() const {
  // @@protoc_insertion_point(field_get:communication.Response.timestamp)
  return timestamp_;
}
inline void Response::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:communication.Response.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace communication

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
